apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodcatalogueapp
  labels:
    app: foodcatalogueapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodcatalogueapp
  template:
    metadata:
      labels:
        app: foodcatalogueapp
    spec:
      containers:
        - name: foodcatalogueapp
          image: sambachennamsetty/food-catalogue-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9093
          env: 
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: secret
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mysql-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: foodcataloguedb_url

---
apiVersion: v1
kind: Service
metadata:
 name: foodcatalogue-service
spec:
  ports:
   - protocol: TCP
     port: 9093
     targetPort: 9093
  selector:
    app: foodcatalogueapp